version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    privileged: true
    user: root
    ports:
      - 8332:8080
      - 50000:50000
    networks:
      - network

  postgres:
    container_name: postgres
    image: postgres:14.5-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8432:8080
    depends_on:
      - postgres
    networks:
      - network
        
  sonarqube:
    container_name: sonarcube
    image: sonarqube:9.6-community
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - network

volumes:
  sonarqube_data:
      driver: local
  sonarqube_extensions:
      driver: local
  sonarqube_logs:
      driver: local
  postgres_data:
      driver: local

networks:
  network:
    driver: bridge
